# Generated by Django 5.2.3 on 2025-07-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_author_user"),
    ]

    operations = []
