# Generated by Django 5.2.4 on 2025-07-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_populate_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_user',
            new_name='author',
        ),
    ]
