# Generated by Django 5.2.3 on 2025-07-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_populate_author_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
    ]
